"""Snapshot tests for the security + package os-shell builtin inspectors.

`add-security-baseline-and-package-inspectors` (os-shell wave-2):
`security.failed_logins`, `security.sudo_history`,
`security.world_writable_dirs`, `pkg.pending_updates`,
`pkg.security_patches`, `pkg.held_back`.

These run the **real** `InspectorRunner` against `ReplayTarget` fixtures (see
`tests/inspectors/fixtures/security/` + `fixtures/pkg/`, generated by
`_record_security_pkg.py`), exercising the full
`preflight → render → collect → parse → findings` path **offline** — zero real
host, zero journal, zero apt/dnf.

The two sampling_window inspectors (`failed_logins` / `sudo_history`) are run
with the SAME frozen clock the recorder used (`FROZEN_DT`) so the rendered
`--since` timestamps match the recorded command byte-for-byte. Every test
asserts `replay.misses == []` so any drift between the rendered command and the
recorded fixture fails loud.

Coverage per inspector (D-5): a finding-trigger fixture (asserts a finding fires
— proving detection, no no-op), an ok fixture (zero findings), and an
**exception** fixture that models the collector's fail-loud path (empty stdout +
non-zero exit → `status=exception`). The exception tests are the spec
false-negative guards (os-shell-inspector-suite「fail-loud 不假阴」/「pkg 无包
管理器非 ok」): a data-source / package-manager failure MUST surface as
`status=exception`, never a silent `status=ok` with a zero count.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import pytest
import structlog

from hostlens.core.config import Settings
from hostlens.inspectors.loader import load_manifest
from hostlens.inspectors.result import InspectorResult
from hostlens.inspectors.runner import InspectorRunner
from hostlens.targets.registry import TargetRegistry
from hostlens.targets.replay import ReplayTarget

_BUILTIN_ROOT = Path(__file__).resolve().parents[2] / "src" / "hostlens" / "inspectors" / "builtin"
_FIXTURE_ROOT = Path(__file__).resolve().parent / "fixtures"

# Must match `_record_security_pkg.FROZEN_DT` so the sampling_window commands
# render identically to the recorded fixtures.
FROZEN_DT = datetime(2026, 1, 2, 12, 0, 0, tzinfo=UTC)


def _runner() -> InspectorRunner:
    return InspectorRunner(
        TargetRegistry(),
        settings=Settings(),
        logger=structlog.get_logger("test"),
        clock=lambda: FROZEN_DT,
    )


async def _run(domain: str, inspector: str, fixture: str) -> tuple[ReplayTarget, InspectorResult]:
    manifest = load_manifest(_BUILTIN_ROOT / domain / f"{inspector}.yaml")
    replay = ReplayTarget("os-host", fixture=_FIXTURE_ROOT / domain / fixture)
    result = await _runner().run(manifest, replay)
    return replay, result


# --------------------------------------------------------------------------- #
# security.failed_logins
# --------------------------------------------------------------------------- #


async def test_failed_logins_burst_detected() -> None:
    replay, result = await _run("security", "failed_logins", "failed_logins_burst.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"failed": 25}
    assert len(result.findings) == 1
    assert result.findings[0].severity == "warning"


def test_failed_logins_double_unit_command_locked() -> None:
    # The cross-distro unit OR (D-6.5) is locked at the command-string level:
    # the recorded main command lists BOTH ssh.service + sshd.service so a
    # RHEL-family host (sshd.service) cannot silently report 0 failures. We
    # assert on the recorded fixture command (the byte-level lock), since the
    # replay path itself does not re-run journalctl's OR semantics.
    import json

    fixture = json.loads(
        (_FIXTURE_ROOT / "security" / "failed_logins_burst.json").read_text(encoding="utf-8")
    )
    main = next(c["cmd"] for c in fixture["commands"] if "--since" in c["cmd"])
    assert "_SYSTEMD_UNIT=ssh.service" in main
    assert "_SYSTEMD_UNIT=sshd.service" in main
    assert "TZ=UTC" in main


async def test_failed_logins_ok_no_findings() -> None:
    replay, result = await _run("security", "failed_logins", "failed_logins_ok.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


async def test_failed_logins_unreachable_is_exception_not_false_negative() -> None:
    replay, result = await _run("security", "failed_logins", "failed_logins_unreachable.json")
    assert replay.misses == []
    # journal unreadable → fail-loud → exception, NOT status=ok failed=0.
    assert result.status == "exception"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# security.sudo_history
# --------------------------------------------------------------------------- #


async def test_sudo_history_spike_detected() -> None:
    replay, result = await _run("security", "sudo_history", "sudo_history_spike.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"invocations": 120}
    assert len(result.findings) == 1


async def test_sudo_history_ok_no_findings() -> None:
    replay, result = await _run("security", "sudo_history", "sudo_history_ok.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


async def test_sudo_history_unreachable_is_exception() -> None:
    replay, result = await _run("security", "sudo_history", "sudo_history_unreachable.json")
    assert replay.misses == []
    assert result.status == "exception"


# --------------------------------------------------------------------------- #
# security.world_writable_dirs
# --------------------------------------------------------------------------- #


async def test_world_writable_dirs_found_detected() -> None:
    replay, result = await _run("security", "world_writable_dirs", "world_writable_dirs_found.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"results": [{"path": "/var/tmp/world-writable"}]}
    assert len(result.findings) == 1


async def test_world_writable_dirs_clean_no_findings() -> None:
    replay, result = await _run("security", "world_writable_dirs", "world_writable_dirs_clean.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


async def test_world_writable_dirs_all_unreachable_is_exception() -> None:
    # D-6.2: rc != 0 AND empty stdout → collector exit 1 → exception (NOT a
    # silent ok with results=[] that would hide an unscannable target).
    replay, result = await _run(
        "security", "world_writable_dirs", "world_writable_dirs_unreachable.json"
    )
    assert replay.misses == []
    assert result.status == "exception"


# --------------------------------------------------------------------------- #
# pkg.pending_updates
# --------------------------------------------------------------------------- #


async def test_pending_updates_available_detected() -> None:
    replay, result = await _run("pkg", "pending_updates", "pending_updates_available.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"pending": 12}
    assert len(result.findings) == 1


async def test_pending_updates_ok_no_findings() -> None:
    replay, result = await _run("pkg", "pending_updates", "pending_updates_ok.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


async def test_pending_updates_no_pkg_mgr_is_exception_not_zero() -> None:
    # Neither apt-get nor dnf (or a present manager whose command failed) →
    # exception, NOT status=ok pending=0 (would falsely read "nothing to
    # update" when collection actually failed). spec「pkg 无包管理器非 ok」.
    replay, result = await _run("pkg", "pending_updates", "pending_updates_no_pkg_mgr.json")
    assert replay.misses == []
    assert result.status == "exception"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# pkg.security_patches
# --------------------------------------------------------------------------- #


async def test_security_patches_pending_detected() -> None:
    # Downstream count + finding lock: given the collector's post-filter count,
    # the parse→DSL→finding chain detects pending patches (non-zero → finding).
    # NOTE: this does NOT execute the `-security` filter regex — under D-7 the
    # fixture records the post-filter `{"patches":N}`, so a mis-written filter
    # is NOT caught here (it would still emit this canned count). The filter
    # regex is command-string-locked + Demo-Path-verified on a real apt/dnf
    # host. See tasks.md deviation registry.
    replay, result = await _run("pkg", "security_patches", "security_patches_pending.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"patches": 4}
    assert len(result.findings) == 1


async def test_security_patches_ok_no_findings() -> None:
    replay, result = await _run("pkg", "security_patches", "security_patches_ok.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


async def test_security_patches_command_failure_is_exception() -> None:
    replay, result = await _run("pkg", "security_patches", "security_patches_failure.json")
    assert replay.misses == []
    assert result.status == "exception"


# --------------------------------------------------------------------------- #
# pkg.held_back
# --------------------------------------------------------------------------- #


async def test_held_back_present_detected() -> None:
    replay, result = await _run("pkg", "held_back", "held_back_present.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"results": [{"package": "nginx"}, {"package": "openssl"}]}
    assert len(result.findings) == 2


async def test_held_back_ok_no_findings() -> None:
    replay, result = await _run("pkg", "held_back", "held_back_ok.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


async def test_held_back_command_failure_is_exception() -> None:
    # apt-mark empty-output ambiguity resolved by exit code (D-6.4): a failed
    # apt-mark → exception, not a silent ok with results=[].
    replay, result = await _run("pkg", "held_back", "held_back_failure.json")
    assert replay.misses == []
    assert result.status == "exception"


@pytest.mark.parametrize(
    ("domain", "inspector", "fixture"),
    [
        ("security", "failed_logins", "failed_logins_unreachable.json"),
        ("security", "sudo_history", "sudo_history_unreachable.json"),
        ("security", "world_writable_dirs", "world_writable_dirs_unreachable.json"),
        ("pkg", "pending_updates", "pending_updates_no_pkg_mgr.json"),
        ("pkg", "security_patches", "security_patches_failure.json"),
        ("pkg", "held_back", "held_back_failure.json"),
    ],
)
async def test_fail_loud_never_silent_ok(domain: str, inspector: str, fixture: str) -> None:
    # spec os-shell-inspector-suite fail-loud guard, swept across all 6: a
    # collection failure MUST be status=exception, never status=ok.
    _, result = await _run(domain, inspector, fixture)
    assert result.status == "exception", f"{inspector} swallowed a collection failure as ok"
