"""Snapshot tests for the wave-1 kernel/system + log builtin inspectors.

`add-os-shell-inspectors-wave1` group 6: `linux.system.reboot_required`,
`linux.kernel.taint`, `linux.kernel.messages`, `log.exception_burst`.

These run the **real** `InspectorRunner` against `ReplayTarget` fixtures (see
`tests/inspectors/fixtures/os_kernel_log/`, generated by
`_record_os_kernel_log.py`), exercising the full
`preflight → render → collect → parse → findings` path **offline** — zero real
host, zero /proc, zero journal.

`linux.kernel.messages` declares a `sampling_window`; the runner is constructed
with the SAME frozen clock the recorder used (`FROZEN_DT`) so the rendered
`--since/--until` timestamps match the recorded command byte-for-byte (design
D-3). Every test asserts `replay.misses == []` so any drift between the rendered
command and the recorded fixture fails loud.

Each inspector has an abnormal-scenario fixture (asserts a finding fires —
proving detection capability, no no-op) and an ok-scenario fixture (asserts zero
findings).
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import structlog

from hostlens.core.config import Settings
from hostlens.inspectors.loader import load_manifest
from hostlens.inspectors.result import InspectorResult
from hostlens.inspectors.runner import InspectorRunner
from hostlens.targets.registry import TargetRegistry
from hostlens.targets.replay import ReplayTarget

_BUILTIN_ROOT = Path(__file__).resolve().parents[2] / "src" / "hostlens" / "inspectors" / "builtin"
_FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "os_kernel_log"

# Must match `_record_os_kernel_log.FROZEN_DT` so the sampling_window command
# renders identically to the recorded fixture.
FROZEN_DT = datetime(2026, 1, 2, 12, 0, 0, tzinfo=UTC)


def _logger() -> structlog.stdlib.BoundLogger:
    return structlog.get_logger("test")  # type: ignore[no-any-return]


def _runner() -> InspectorRunner:
    return InspectorRunner(
        TargetRegistry(), settings=Settings(), logger=_logger(), clock=lambda: FROZEN_DT
    )


async def _run(
    domain: str,
    inspector: str,
    fixture: str,
    parameters: dict[str, object] | None = None,
) -> tuple[ReplayTarget, InspectorResult]:
    manifest = load_manifest(_BUILTIN_ROOT / domain / f"{inspector}.yaml")
    replay = ReplayTarget("os-host", fixture=_FIXTURE_DIR / fixture)
    result = await _runner().run(manifest, replay, parameters=parameters)
    return replay, result


# --------------------------------------------------------------------------- #
# linux.system.reboot_required
# --------------------------------------------------------------------------- #


async def test_reboot_required_pending_detected() -> None:
    replay, result = await _run(
        "linux", "system_reboot_required", "system_reboot_required_pending.json"
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "reboot_required": True,
        "reason": "*** System restart required ***",
        "pkgs": "linux-image-6.8.0-45-generic libssl3",
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "warning",
            "Reboot required: *** System restart required *** "
            "(pending packages: linux-image-6.8.0-45-generic libssl3)",
        ),
    ]


async def test_reboot_required_ok_no_findings() -> None:
    replay, result = await _run("linux", "system_reboot_required", "system_reboot_required_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.kernel.taint
# --------------------------------------------------------------------------- #


async def test_kernel_taint_tainted_detected() -> None:
    replay, result = await _run("linux", "kernel_taint", "kernel_taint_tainted.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "tainted": 4097,
        "flags": "proprietary-module-loaded,out-of-tree-module",
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "warning",
            "Kernel is tainted (tainted=4097): proprietary-module-loaded,out-of-tree-module",
        ),
    ]


async def test_kernel_taint_ok_no_findings() -> None:
    replay, result = await _run("linux", "kernel_taint", "kernel_taint_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.kernel.messages (sampling_window)
# --------------------------------------------------------------------------- #


async def test_kernel_messages_burst_detected() -> None:
    replay, result = await _run("linux", "kernel_messages", "kernel_messages_burst.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"error_count": "37", "window_seconds": "300"}
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "37 kernel error messages in the last 300s"),
    ]


async def test_kernel_messages_ok_no_findings() -> None:
    replay, result = await _run("linux", "kernel_messages", "kernel_messages_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# log.exception_burst
# --------------------------------------------------------------------------- #


async def test_exception_burst_detected() -> None:
    replay, result = await _run(
        "log",
        "exception_burst",
        "exception_burst_burst.json",
        parameters={"log_path": "/var/log/app.log"},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "results": [
            {"signature": "java.lang.NullPointerException", "count": 42},
            {"signature": "java.lang.OutOfMemoryError", "count": 3},
        ],
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("warning", "Exception burst: java.lang.NullPointerException occurred 42 times"),
    ]


async def test_exception_burst_ok_no_findings() -> None:
    replay, result = await _run(
        "log",
        "exception_burst",
        "exception_burst_ok.json",
        parameters={"log_path": "/var/log/app.log"},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []
