"""Snapshot tests for the wave-1 disk + filesystem builtin inspectors.

`add-os-shell-inspectors-wave1` group 2: `linux.disk.io`, `linux.disk.smart`,
`linux.fs.mount_health`, `linux.fs.logrotate`.

These run the **real** `InspectorRunner` against `ReplayTarget` fixtures (see
`tests/inspectors/fixtures/os_disk_fs/`, generated by `_record_os_disk_fs.py`),
so they exercise the full `preflight → render → collect → parse → findings`
path **offline** — zero real host, zero /proc, zero /sys read. The OS probes are
Linux-only; the recorder crafts the JSON each collector pipeline would emit per
scenario.

Each inspector has BOTH an abnormal-scenario fixture (asserts a finding fires —
proving the inspector can detect the target fault, no no-op) and an ok-scenario
fixture (asserts zero findings). Every test asserts `replay.misses == []` so a
drift between the rendered command and the recorded fixture fails loud.
"""

from __future__ import annotations

from pathlib import Path

import structlog

from hostlens.core.config import Settings
from hostlens.inspectors.loader import load_manifest
from hostlens.inspectors.result import InspectorResult
from hostlens.inspectors.runner import InspectorRunner
from hostlens.targets.registry import TargetRegistry
from hostlens.targets.replay import ReplayTarget

_BUILTIN_DIR = (
    Path(__file__).resolve().parents[2] / "src" / "hostlens" / "inspectors" / "builtin" / "linux"
)
_FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "os_disk_fs"


def _logger() -> structlog.stdlib.BoundLogger:
    return structlog.get_logger("test")  # type: ignore[no-any-return]


def _runner() -> InspectorRunner:
    return InspectorRunner(TargetRegistry(), settings=Settings(), logger=_logger())


async def _run(inspector: str, fixture: str) -> tuple[ReplayTarget, InspectorResult]:
    manifest = load_manifest(_BUILTIN_DIR / f"{inspector}.yaml")
    replay = ReplayTarget("os-host", fixture=_FIXTURE_DIR / fixture)
    result = await _runner().run(manifest, replay)
    return replay, result


# --------------------------------------------------------------------------- #
# linux.disk.io
# --------------------------------------------------------------------------- #


async def test_disk_io_saturated_detected() -> None:
    replay, result = await _run("disk_io", "disk_io_saturated.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "results": [
            {"device": "nvme0n1", "util_pct": "12.0", "await_ms": "0.40", "ops": 300},
            {"device": "sda", "util_pct": "98.5", "await_ms": "42.30", "ops": 1200},
        ]
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "Disk sda saturated at 98.5% IO utilisation (await=42.30ms)"),
    ]


async def test_disk_io_high_latency_detected() -> None:
    replay, result = await _run("disk_io", "disk_io_high_latency.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert [(f.severity, f.message) for f in result.findings] == [
        ("warning", "Disk sdb high latency: 75.50ms average request time"),
    ]


async def test_disk_io_ok_no_findings() -> None:
    replay, result = await _run("disk_io", "disk_io_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.disk.smart
# --------------------------------------------------------------------------- #


async def test_disk_smart_failed_detected() -> None:
    replay, result = await _run("disk_smart", "disk_smart_failed.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "results": [
            {"device": "sda", "rotational": 1, "size_gib": "931.5", "smart_health": "FAILED"},
            {"device": "nvme0n1", "rotational": 0, "size_gib": "476.9", "smart_health": "PASSED"},
        ]
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "Disk sda reports SMART overall-health FAILED (931.5GiB)"),
    ]


async def test_disk_smart_ok_no_findings() -> None:
    replay, result = await _run("disk_smart", "disk_smart_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.fs.mount_health
# --------------------------------------------------------------------------- #


async def test_fs_mount_health_readonly_detected() -> None:
    replay, result = await _run("fs_mount_health", "fs_mount_health_readonly.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "results": [
            {"target": "/", "source": "/dev/sda1", "fstype": "ext4", "read_only": False},
            {"target": "/data", "source": "/dev/sdb1", "fstype": "xfs", "read_only": True},
        ]
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "Filesystem /data (/dev/sdb1, xfs) is mounted read-only"),
    ]


async def test_fs_mount_health_ok_no_findings() -> None:
    replay, result = await _run("fs_mount_health", "fs_mount_health_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.fs.logrotate
# --------------------------------------------------------------------------- #


async def test_fs_logrotate_stale_detected() -> None:
    replay, result = await _run("fs_logrotate", "fs_logrotate_stale.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "days_since_last": "21.0",
        "last_date": "2024-1-15",
        "tracked_files": 12,
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "critical",
            "logrotate stalled: last rotation 21.0 days ago (2024-1-15, 12 files tracked)",
        ),
    ]


async def test_fs_logrotate_ok_no_findings() -> None:
    replay, result = await _run("fs_logrotate", "fs_logrotate_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []
