"""Snapshot tests for the wave-1 process-domain builtin inspectors.

`add-os-shell-inspectors-wave1` group 4 (process domain): `linux.process.zombies`,
`linux.process.total`, `linux.process.critical_alive`.

These run the **real** `InspectorRunner` against `ReplayTarget` fixtures (see
`tests/inspectors/fixtures/os_process/`, generated by `_record_os_process.py`),
so they exercise the full `preflight → render → collect → parse → findings` path
**offline** — zero real host, zero /proc read, zero `ps`/`pgrep`. The OS probes
are Linux-only; the recorder crafts the JSON each collector pipeline would emit
per scenario.

Each inspector has BOTH an abnormal-scenario fixture (asserts a finding fires —
proving the inspector can detect the target fault, no no-op) and an ok-scenario
fixture (asserts zero findings). `linux.process.critical_alive` adds an
injection-safety scenario proving a path-like name is interpolated as one shell
word. Every test asserts `replay.misses == []` so a drift between the rendered
command and the recorded fixture fails loud. The parameterised inspector is run
with the SAME `parameters` the recorder used so the rendered command matches.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import structlog

from hostlens.core.config import Settings
from hostlens.inspectors.loader import load_manifest
from hostlens.inspectors.result import InspectorResult
from hostlens.inspectors.runner import InspectorRunner
from hostlens.targets.registry import TargetRegistry
from hostlens.targets.replay import ReplayTarget

_BUILTIN_DIR = (
    Path(__file__).resolve().parents[2] / "src" / "hostlens" / "inspectors" / "builtin" / "linux"
)
_FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "os_process"


def _logger() -> structlog.stdlib.BoundLogger:
    return structlog.get_logger("test")  # type: ignore[no-any-return]


def _runner() -> InspectorRunner:
    return InspectorRunner(TargetRegistry(), settings=Settings(), logger=_logger())


async def _run(
    inspector: str,
    fixture: str,
    *,
    parameters: dict[str, Any] | None = None,
) -> tuple[ReplayTarget, InspectorResult]:
    manifest = load_manifest(_BUILTIN_DIR / f"{inspector}.yaml")
    replay = ReplayTarget("os-host", fixture=_FIXTURE_DIR / fixture)
    result = await _runner().run(manifest, replay, parameters=parameters)
    return replay, result


# --------------------------------------------------------------------------- #
# linux.process.zombies
# --------------------------------------------------------------------------- #


async def test_process_zombies_present_detected() -> None:
    replay, result = await _run("process_zombies", "process_zombies_present.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "zombie_count": 3,
        "results": [
            {"pid": 4242, "comm": "defunct-a"},
            {"pid": 4243, "comm": "defunct-b"},
            {"pid": 4244, "comm": "defunct-c"},
        ],
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("warning", "3 zombie process(es) present (defunct, not reaped)"),
        ("info", "zombie process pid=4242 (defunct-a)"),
        ("info", "zombie process pid=4243 (defunct-b)"),
        ("info", "zombie process pid=4244 (defunct-c)"),
    ]


async def test_process_zombies_ok_no_findings() -> None:
    replay, result = await _run("process_zombies", "process_zombies_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"zombie_count": 0, "results": []}
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.process.total
# --------------------------------------------------------------------------- #


async def test_process_total_near_pid_max_detected() -> None:
    replay, result = await _run("process_total", "process_total_near_pid_max.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "total": 30000,
        "pid_max": 32768,
        "used_pct": "91.6",
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "Process table near pid_max: 30000/32768 (91.6% used)"),
    ]


async def test_process_total_ok_no_findings() -> None:
    replay, result = await _run("process_total", "process_total_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "total": 250,
        "pid_max": 32768,
        "used_pct": "0.8",
    }
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.process.critical_alive
# --------------------------------------------------------------------------- #


async def test_process_critical_alive_missing_detected() -> None:
    replay, result = await _run(
        "process_critical_alive",
        "process_critical_alive_missing.json",
        parameters={"names": ["sshd", "nginx"]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "results": [
            {"name": "sshd", "alive": True},
            {"name": "nginx", "alive": False},
        ],
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "Critical process nginx is not alive"),
    ]


async def test_process_critical_alive_ok_no_findings() -> None:
    replay, result = await _run(
        "process_critical_alive",
        "process_critical_alive_ok.json",
        parameters={"names": ["sshd", "nginx"]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


async def test_process_critical_alive_injection_safe() -> None:
    replay, result = await _run(
        "process_critical_alive",
        "process_critical_alive_injection.json",
        parameters={"names": ["/usr/sbin/cron-d.worker"]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "results": [
            {"name": "/usr/sbin/cron-d.worker", "alive": False},
        ],
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "Critical process /usr/sbin/cron-d.worker is not alive"),
    ]
