"""Snapshot tests for the wave-1 network / DNS / NTP builtin inspectors.

`add-os-shell-inspectors-wave1` group 3: `net.connections`,
`net.listening_ports`, `net.dns.resolve`, `net.ntp.drift`.

These run the **real** `InspectorRunner` against `ReplayTarget` fixtures (see
`tests/inspectors/fixtures/os_net/`, generated by `_record_os_net.py`), so they
exercise the full `preflight → render → collect → parse → findings` path
**offline** — zero real host, zero `ss`/`dig`/`chronyc`. The probes are
Linux-only; the recorder crafts the JSON each collector pipeline would emit per
scenario.

Each inspector has BOTH an abnormal-scenario fixture (asserts a finding fires —
proving it can detect the target fault, no no-op) and an ok-scenario fixture
(asserts zero findings). `net.dns.resolve` additionally has an injection-safety
test: a malicious `names` payload is rejected by the parameter `pattern` BEFORE
any command renders (no exec ever happens). Every replay test asserts
`replay.misses == []` so a drift between rendered command and recorded fixture
fails loud.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, ClassVar

import structlog

from hostlens.core.config import Settings
from hostlens.inspectors.loader import load_manifest
from hostlens.inspectors.result import InspectorResult
from hostlens.inspectors.runner import InspectorRunner
from hostlens.targets.base import Capability, ExecResult
from hostlens.targets.registry import TargetRegistry
from hostlens.targets.replay import ReplayTarget

_BUILTIN_DIR = (
    Path(__file__).resolve().parents[2] / "src" / "hostlens" / "inspectors" / "builtin" / "net"
)
_FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "os_net"


def _logger() -> structlog.stdlib.BoundLogger:
    return structlog.get_logger("test")  # type: ignore[no-any-return]


def _runner() -> InspectorRunner:
    return InspectorRunner(TargetRegistry(), settings=Settings(), logger=_logger())


async def _run(
    inspector: str,
    fixture: str,
    parameters: dict[str, Any] | None = None,
) -> tuple[ReplayTarget, InspectorResult]:
    manifest = load_manifest(_BUILTIN_DIR / f"{inspector}.yaml")
    replay = ReplayTarget("os-host", fixture=_FIXTURE_DIR / fixture)
    result = await _runner().run(manifest, replay, parameters=parameters)
    return replay, result


# --------------------------------------------------------------------------- #
# net.connections
# --------------------------------------------------------------------------- #


async def test_connections_close_wait_leak_detected() -> None:
    replay, result = await _run("connections", "connections_close_wait_leak.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "total": 1234,
        "established": 420,
        "time_wait": 150,
        "close_wait": 512,
        "syn_sent": 2,
        "syn_recv": 1,
        "fin_wait": 3,
        "listen": 45,
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "critical",
            "CLOSE_WAIT backlog of 512 sockets; application is leaking unclosed connections",
        ),
    ]


async def test_connections_ok_no_findings() -> None:
    replay, result = await _run("connections", "connections_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# net.listening_ports
# --------------------------------------------------------------------------- #


async def test_listening_ports_unexpected_detected() -> None:
    replay, result = await _run(
        "listening_ports",
        "listening_ports_unexpected.json",
        parameters={"allowed_ports": [22, 443]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "results": [
            {"address": "0.0.0.0", "port": 22, "wildcard": True, "process": "sshd"},
            {"address": "0.0.0.0", "port": 6379, "wildcard": True, "process": "redis-server"},
            {"address": "127.0.0.1", "port": 5432, "wildcard": False, "process": "postgres"},
        ],
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "warning",
            "Unexpected public listener on port 6379 (0.0.0.0, process=redis-server)",
        ),
    ]


async def test_listening_ports_ok_no_findings() -> None:
    replay, result = await _run(
        "listening_ports",
        "listening_ports_ok.json",
        parameters={"allowed_ports": [22, 443]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# net.dns.resolve
# --------------------------------------------------------------------------- #


async def test_dns_resolve_failure_detected() -> None:
    replay, result = await _run(
        "dns_resolve",
        "dns_resolve_failure.json",
        parameters={"names": ["example.com", "nonexistent.invalid"]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "results": [
            {"name": "example.com", "resolved": True, "address": "93.184.216.34"},
            {"name": "nonexistent.invalid", "resolved": False, "address": ""},
        ],
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "DNS name nonexistent.invalid failed to resolve (no A record)"),
    ]


async def test_dns_resolve_ok_no_findings() -> None:
    replay, result = await _run(
        "dns_resolve",
        "dns_resolve_ok.json",
        parameters={"names": ["example.com"]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


async def test_dns_resolve_injection_safe_renders_quoted() -> None:
    """A benign name renders into a `shlex.quote`-wrapped loop word.

    Captured at record time the rendered command embeds the name as a single
    quoted word (`for nm in safe-host.example`), proving the `| map('sh')`
    filter is on the interpolation path. Replay re-renders the same command
    and must hit the recorded fixture byte-for-byte.
    """

    replay, result = await _run(
        "dns_resolve",
        "dns_resolve_injection_safe.json",
        parameters={"names": ["safe-host.example"]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []
    # The recorded collector command must carry the name through shlex.quote /
    # the `| map('sh')` filter (here a no-special-char name needs no quoting,
    # but the word must appear exactly once in the rendered loop header). Read
    # the fixture JSON directly — ReplayTarget keys commands by SHA256.
    fixture = json.loads(
        (_FIXTURE_DIR / "dns_resolve_injection_safe.json").read_text(encoding="utf-8")
    )
    dns_cmd = next(c["cmd"] for c in fixture["commands"] if "dig +short" in c["cmd"])
    assert "for nm in safe-host.example;" in dns_cmd


class _ProbeOnlyTarget:
    """Target that answers preflight probes but rejects the main collector cmd.

    Used by the injection-payload test. The runner's preflight (binary `command
    -v X` / file `[ -r P ]` probes, step 5) runs BEFORE parameter validation
    (step 7), so those probes legitimately reach `exec`. But the rendered
    collector command — the only place the malicious `names` element could land
    in a shell-evaluated position — must NEVER run, because parameter validation
    rejects the payload first. Any non-probe `exec` therefore fails loud.
    """

    type = "local"
    name = "probe-only-host"
    capabilities: ClassVar[set[Capability]] = {Capability.SHELL}

    async def exec(
        self,
        cmd: str,
        *,
        timeout: int,
        env: dict[str, str] | None = None,
    ) -> ExecResult:
        del timeout, env
        if cmd.startswith("command -v "):
            binary = cmd[len("command -v ") :].strip().strip("'\"")
            return ExecResult(
                exit_code=0,
                stdout=f"/usr/bin/{binary}\n",
                stderr="",
                duration_seconds=0.0,
                timed_out=False,
            )
        if cmd.startswith("[ -r "):
            return ExecResult(
                exit_code=0, stdout="", stderr="", duration_seconds=0.0, timed_out=False
            )
        raise AssertionError(
            f"collector command must not be reached for a rejected payload: {cmd!r}"
        )

    async def read_file(self, path: str) -> bytes:
        raise AssertionError(f"read_file must not be reached: {path!r}")


async def test_dns_resolve_injection_payload_rejected_before_command() -> None:
    """A shell-injection payload in `names` is rejected by the schema pattern.

    The payload `'; whoami; #` cannot satisfy `^[a-zA-Z0-9.-]+$`, so the runner
    short-circuits to `status=exception` (parameter_validation_failed) before
    the collector command is rendered or run — the malicious string never
    reaches a shell-evaluated position (`_ProbeOnlyTarget` asserts the main
    command is never exec'd).
    """

    manifest = load_manifest(_BUILTIN_DIR / "dns_resolve.yaml")
    target = _ProbeOnlyTarget()
    result = await _runner().run(
        manifest,
        target,  # type: ignore[arg-type]
        parameters={"names": ["'; whoami; #"]},
    )

    assert result.status == "exception"
    assert result.error is not None
    assert result.error.startswith("parameter_validation_failed")
    assert result.findings == []


# --------------------------------------------------------------------------- #
# net.ntp.drift
# --------------------------------------------------------------------------- #


async def test_ntp_drift_high_detected() -> None:
    replay, result = await _run("ntp_drift", "ntp_drift_high.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "offset_seconds": 2.345678901,
        "abs_offset_seconds": 2.345678901,
        "leap_status": "Normal",
        "synced": True,
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "Clock drift 2.345678901s exceeds 1s (leap status: Normal)"),
    ]


async def test_ntp_drift_ok_no_findings() -> None:
    replay, result = await _run("ntp_drift", "ntp_drift_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []
