"""Snapshot tests for the wave-1 network / DNS / NTP builtin inspectors.

`add-os-shell-inspectors-wave1` group 3: `net.connections`,
`net.listening_ports`, `net.dns.resolve`, `net.ntp.drift`.

These run the **real** `InspectorRunner` against `ReplayTarget` fixtures (see
`tests/inspectors/fixtures/os_net/`, generated by `_record_os_net.py`), so they
exercise the full `preflight → render → collect → parse → findings` path
**offline** — zero real host, zero `ss`/`dig`/`chronyc`. The probes are
Linux-only; the recorder crafts the JSON each collector pipeline would emit per
scenario.

Each inspector has BOTH an abnormal-scenario fixture (asserts a finding fires —
proving it can detect the target fault, no no-op) and an ok-scenario fixture
(asserts zero findings). `net.dns.resolve` additionally has an injection-safety
test: a malicious `names` payload is rejected by the parameter `pattern` BEFORE
any command renders (no exec ever happens). Every replay test asserts
`replay.misses == []` so a drift between rendered command and recorded fixture
fails loud.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, ClassVar

import structlog

from hostlens.core.config import Settings
from hostlens.inspectors.loader import load_manifest
from hostlens.inspectors.registry import build_registry_from_search_paths
from hostlens.inspectors.result import InspectorResult
from hostlens.inspectors.runner import InspectorRunner
from hostlens.targets.base import Capability, ExecResult
from hostlens.targets.registry import TargetRegistry
from hostlens.targets.replay import ReplayTarget

_BUILTIN_DIR = (
    Path(__file__).resolve().parents[2] / "src" / "hostlens" / "inspectors" / "builtin" / "net"
)
_FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "os_net"


def _logger() -> structlog.stdlib.BoundLogger:
    return structlog.get_logger("test")  # type: ignore[no-any-return]


def _runner() -> InspectorRunner:
    return InspectorRunner(TargetRegistry(), settings=Settings(), logger=_logger())


async def _run(
    inspector: str,
    fixture: str,
    parameters: dict[str, Any] | None = None,
) -> tuple[ReplayTarget, InspectorResult]:
    manifest = load_manifest(_BUILTIN_DIR / f"{inspector}.yaml")
    replay = ReplayTarget("os-host", fixture=_FIXTURE_DIR / fixture)
    result = await _runner().run(manifest, replay, parameters=parameters)
    return replay, result


# --------------------------------------------------------------------------- #
# net.connections
# --------------------------------------------------------------------------- #


async def test_connections_close_wait_leak_detected() -> None:
    replay, result = await _run("connections", "connections_close_wait_leak.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "total": 1234,
        "established": 420,
        "time_wait": 150,
        "close_wait": 512,
        "syn_sent": 2,
        "syn_recv": 1,
        "fin_wait": 3,
        "listen": 45,
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "critical",
            "CLOSE_WAIT backlog of 512 sockets; application is leaking unclosed connections",
        ),
    ]


async def test_connections_ok_no_findings() -> None:
    replay, result = await _run("connections", "connections_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# net.listening_ports
# --------------------------------------------------------------------------- #


async def test_listening_ports_unexpected_detected() -> None:
    replay, result = await _run(
        "listening_ports",
        "listening_ports_unexpected.json",
        parameters={"allowed_ports": [22, 443]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "results": [
            {"address": "0.0.0.0", "port": 22, "wildcard": True, "process": "sshd"},
            {"address": "0.0.0.0", "port": 6379, "wildcard": True, "process": "redis-server"},
            {"address": "127.0.0.1", "port": 5432, "wildcard": False, "process": "postgres"},
        ],
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "warning",
            "Unexpected public listener on port 6379 (0.0.0.0, process=redis-server)",
        ),
    ]


async def test_listening_ports_ok_no_findings() -> None:
    replay, result = await _run(
        "listening_ports",
        "listening_ports_ok.json",
        parameters={"allowed_ports": [22, 443]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --- allowed_processes exemption (add-schedule-inspector-parameters group C) - #
#
# The collector command is parameter-independent (`allowed_processes` is a
# Finding DSL membership term, never interpolated into the shell), so the same
# recorded `listening_ports_unexpected.json` fixture (wildcard sshd:22 and
# redis-server:6379) serves every `allowed_processes` variant — only the
# parameters passed to `runner.run` change. These tests are the explicit
# security-semantics anchors from design decision 4 / 5: process exemption,
# port exemption (original path, unchanged), and the empty-process conservative
# boundary.


def test_listening_ports_manifest_builds_with_string_array_pattern() -> None:
    """The string-typed `allowed_processes` array must carry an items `pattern`.

    The inspector-authoring-contract makes a string-typed array WITHOUT a
    `pattern`/`enum` a fatal load error for a builtin (`registry.build` would
    collect it / crash). Building the builtin registry and asserting
    `errors == []` proves the new `^[A-Za-z0-9._@-]+$` pattern satisfies the
    contract and `net.listening_ports` still loads.
    """

    result = build_registry_from_search_paths([], settings=Settings())
    assert result.errors == []
    assert "net.listening_ports" in result.registry.names()


async def test_listening_ports_process_exempt_no_finding() -> None:
    """A wildcard listener whose process is in `allowed_processes` is exempt."""

    replay, result = await _run(
        "listening_ports",
        "listening_ports_unexpected.json",
        parameters={"allowed_ports": [], "allowed_processes": ["sshd", "redis-server"]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    # Both wildcard listeners (sshd:22, redis-server:6379) are process-exempt;
    # the non-wildcard postgres:5432 never qualified.
    assert result.findings == []


async def test_listening_ports_process_not_exempt_warns() -> None:
    """A wildcard listener whose process is NOT in `allowed_processes` warns."""

    replay, result = await _run(
        "listening_ports",
        "listening_ports_unexpected.json",
        parameters={"allowed_ports": [], "allowed_processes": ["sshd"]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    # sshd:22 is process-exempt; redis-server:6379 is not → single warning.
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "warning",
            "Unexpected public listener on port 6379 (0.0.0.0, process=redis-server)",
        ),
    ]


async def test_listening_ports_port_exempt_still_no_finding() -> None:
    """The original `allowed_ports` path still exempts a wildcard port.

    With an empty `allowed_processes`, exempting both wildcard ports by number
    must still produce zero findings (the new `when` conjunct does not regress
    the port-allowlist path).
    """

    replay, result = await _run(
        "listening_ports",
        "listening_ports_unexpected.json",
        parameters={"allowed_ports": [22, 6379], "allowed_processes": []},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


async def test_listening_ports_empty_process_conservative_warns() -> None:
    """An empty process name is conservatively treated as UNexempt.

    A non-privileged probe cannot read another user's socket identity, so the
    `process` field can come back empty. `"" not in <non-empty allowlist>` is
    true, so the wildcard listener still warns — unattributable wildcard
    listeners must stay visible (design decision 4 boundary).
    """

    replay, result = await _run(
        "listening_ports",
        "listening_ports_empty_process.json",
        parameters={"allowed_ports": [], "allowed_processes": ["node-exporter"]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "warning",
            "Unexpected public listener on port 9100 (0.0.0.0, process=)",
        ),
    ]


# --------------------------------------------------------------------------- #
# net.dns.resolve
# --------------------------------------------------------------------------- #


async def test_dns_resolve_failure_detected() -> None:
    replay, result = await _run(
        "dns_resolve",
        "dns_resolve_failure.json",
        parameters={"names": ["example.com", "nonexistent.invalid"]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "results": [
            {"name": "example.com", "resolved": True, "address": "93.184.216.34"},
            {"name": "nonexistent.invalid", "resolved": False, "address": ""},
        ],
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "DNS name nonexistent.invalid failed to resolve (no A record)"),
    ]


async def test_dns_resolve_ok_no_findings() -> None:
    replay, result = await _run(
        "dns_resolve",
        "dns_resolve_ok.json",
        parameters={"names": ["example.com"]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


async def test_dns_resolve_injection_safe_renders_quoted() -> None:
    """A benign name renders into a `shlex.quote`-wrapped loop word.

    Captured at record time the rendered command embeds the name as a single
    quoted word (`for nm in safe-host.example`), proving the `| map('sh')`
    filter is on the interpolation path. Replay re-renders the same command
    and must hit the recorded fixture byte-for-byte.
    """

    replay, result = await _run(
        "dns_resolve",
        "dns_resolve_injection_safe.json",
        parameters={"names": ["safe-host.example"]},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []
    # The recorded collector command must carry the name through shlex.quote /
    # the `| map('sh')` filter (here a no-special-char name needs no quoting,
    # but the word must appear exactly once in the rendered loop header). Read
    # the fixture JSON directly — ReplayTarget keys commands by SHA256.
    fixture = json.loads(
        (_FIXTURE_DIR / "dns_resolve_injection_safe.json").read_text(encoding="utf-8")
    )
    dns_cmd = next(c["cmd"] for c in fixture["commands"] if "dig +short" in c["cmd"])
    assert "for nm in safe-host.example;" in dns_cmd


class _ProbeOnlyTarget:
    """Target that answers preflight probes but rejects the main collector cmd.

    Used by the injection-payload test. The runner's preflight (binary `command
    -v X` / file `[ -r P ]` probes, step 5) runs BEFORE parameter validation
    (step 7), so those probes legitimately reach `exec`. But the rendered
    collector command — the only place the malicious `names` element could land
    in a shell-evaluated position — must NEVER run, because parameter validation
    rejects the payload first. Any non-probe `exec` therefore fails loud.
    """

    type = "local"
    name = "probe-only-host"
    capabilities: ClassVar[set[Capability]] = {Capability.SHELL}

    async def exec(
        self,
        cmd: str,
        *,
        timeout: int,
        env: dict[str, str] | None = None,
    ) -> ExecResult:
        del timeout, env
        if cmd.startswith("command -v "):
            binary = cmd[len("command -v ") :].strip().strip("'\"")
            return ExecResult(
                exit_code=0,
                stdout=f"/usr/bin/{binary}\n",
                stderr="",
                duration_seconds=0.0,
                timed_out=False,
            )
        if cmd.startswith("[ -r "):
            return ExecResult(
                exit_code=0, stdout="", stderr="", duration_seconds=0.0, timed_out=False
            )
        raise AssertionError(
            f"collector command must not be reached for a rejected payload: {cmd!r}"
        )

    async def read_file(self, path: str) -> bytes:
        raise AssertionError(f"read_file must not be reached: {path!r}")


async def test_dns_resolve_injection_payload_rejected_before_command() -> None:
    """A shell-injection payload in `names` is rejected by the schema pattern.

    The payload `'; whoami; #` cannot satisfy `^[a-zA-Z0-9.-]+$`, so the runner
    short-circuits to `status=exception` (parameter_validation_failed) before
    the collector command is rendered or run — the malicious string never
    reaches a shell-evaluated position (`_ProbeOnlyTarget` asserts the main
    command is never exec'd).
    """

    manifest = load_manifest(_BUILTIN_DIR / "dns_resolve.yaml")
    target = _ProbeOnlyTarget()
    result = await _runner().run(
        manifest,
        target,  # type: ignore[arg-type]
        parameters={"names": ["'; whoami; #"]},
    )

    assert result.status == "exception"
    assert result.error is not None
    assert result.error.startswith("parameter_validation_failed")
    assert result.findings == []


# --------------------------------------------------------------------------- #
# net.ntp.drift
# --------------------------------------------------------------------------- #


async def test_ntp_drift_high_detected() -> None:
    replay, result = await _run("ntp_drift", "ntp_drift_high.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "offset_seconds": 2.345678901,
        "abs_offset_seconds": 2.345678901,
        "leap_status": "Normal",
        "synced": True,
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "Clock drift 2.345678901s exceeds 1s (leap status: Normal)"),
    ]


async def test_ntp_drift_ok_no_findings() -> None:
    replay, result = await _run("ntp_drift", "ntp_drift_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# net.tls.chain_validity (add-tls-chain-validity-inspector)
# --------------------------------------------------------------------------- #
#
# These fixtures are crafted `openssl s_client` stdout (NOT JSON) — the
# inspector parses with `format: raw` + a `raw_extract_regex` that requires a
# `-----BEGIN CERTIFICATE-----` marker BEFORE the "Verify return code:" footer
# (the B3 false-negative guard, design D9). Because `parse_raw`'s `re.search`
# runs offline, the B3 guard is *offline-provable*: a no-cert stdout that still
# carries "Verify return code: 0" misses the regex → null → output_schema
# rejects → status=exception. Both OpenSSL 3.x and LibreSSL footer wordings are
# sampled (valid + broken each) to lock the regex's cross-implementation
# stability (design R1).


async def test_tls_chain_validity_valid_openssl_ok() -> None:
    replay, result = await _run(
        "tls_chain_validity",
        "tls_chain_validity_valid_openssl.json",
        parameters={"endpoint": "example.com:443"},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"verify_code": "0", "reason": "ok"}
    assert result.findings == []


async def test_tls_chain_validity_valid_libressl_ok() -> None:
    """LibreSSL footer wording (macOS local target) parses to the same ok."""

    replay, result = await _run(
        "tls_chain_validity",
        "tls_chain_validity_valid_libressl.json",
        parameters={"endpoint": "example.org:443"},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"verify_code": "0", "reason": "ok"}
    assert result.findings == []


async def test_tls_chain_validity_broken_openssl_critical() -> None:
    """Missing intermediate CA (code 20) → single critical finding."""

    replay, result = await _run(
        "tls_chain_validity",
        "tls_chain_validity_broken_openssl.json",
        parameters={"endpoint": "incomplete-chain.example:443"},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "verify_code": "20",
        "reason": "unable to get local issuer certificate",
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "critical",
            "TLS 证书链验证失败 (code 20: unable to get local issuer certificate)",
        ),
    ]


async def test_tls_chain_validity_broken_libressl_critical() -> None:
    """LibreSSL self-signed-in-chain (code 19, hyphenated reason) → critical.

    Locks the `raw_extract_regex` against LibreSSL's reason wording (hyphenated
    `self-signed certificate ...`) and confirms the str DSL `verify_code != '0'`
    fires for a non-zero code.
    """

    replay, result = await _run(
        "tls_chain_validity",
        "tls_chain_validity_broken_libressl.json",
        parameters={"endpoint": "self-signed.example:443"},
    )

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "verify_code": "19",
        "reason": "self-signed certificate in certificate chain",
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "critical",
            "TLS 证书链验证失败 (code 19: self-signed certificate in certificate chain)",
        ),
    ]


async def test_tls_chain_validity_no_cert_exception() -> None:
    """B3 false-negative guard (offline-provable).

    A non-TLS port / half-handshake produces "Verify return code: 0 (ok)" but
    NO `-----BEGIN CERTIFICATE-----` marker. The `raw_extract_regex` requires
    the marker before the Verify line, so it misses → `{verify_code: null}` →
    `output_schema` (`required` + `type: string`) rejects null → exception.
    The guard lives in the parser regex, so `parse_raw`'s `re.search` exercises
    it offline — no real host needed. This proves we never report a non-TLS
    port as "chain valid".
    """

    replay, result = await _run(
        "tls_chain_validity",
        "tls_chain_validity_no_cert.json",
        parameters={"endpoint": "127.0.0.1:22"},
    )

    assert replay.misses == []
    assert result.status == "exception"
    assert result.findings == []


async def test_tls_chain_validity_empty_stdout_exception() -> None:
    """Unreachable endpoint → empty stdout → no PEM, no Verify line → exception.

    We never treat an endpoint we could not reach as "chain valid".
    """

    replay, result = await _run(
        "tls_chain_validity",
        "tls_chain_validity_empty.json",
        parameters={"endpoint": "10.255.255.1:443"},
    )

    assert replay.misses == []
    assert result.status == "exception"
    assert result.findings == []


# --- command-string locks (offline cannot run the collector shell, D-7) ----- #


def _tls_main_cmd(fixture: str) -> str:
    """Return the recorded `openssl s_client` collector command for a fixture.

    ReplayTarget keys commands by SHA256, so we read the fixture JSON directly
    and pick the main collect command (the one carrying `openssl s_client`).
    """

    data = json.loads((_FIXTURE_DIR / fixture).read_text(encoding="utf-8"))
    return next(c["cmd"] for c in data["commands"] if "openssl s_client" in c["cmd"])


def test_tls_chain_validity_endpoint_is_sh_quoted() -> None:
    """`endpoint` flows through `| sh` (shlex.quote) — second defense line.

    Even if the parameter `pattern` were ever loosened, the collector quotes the
    endpoint via the `| sh` filter. A benign `host:port` needs no quoting, but
    the rendered command must carry the endpoint exactly where `{{ endpoint | sh }}`
    interpolates (the `-connect` argument and the `printf '%s'` host extraction).
    """

    cmd = _tls_main_cmd("tls_chain_validity_valid_openssl.json")
    assert "-connect example.com:443" in cmd
    assert "printf '%s' example.com:443" in cmd


def test_tls_chain_validity_sni_case_branch_is_locked_in_command() -> None:
    """SNI selection is a shell `case` branch (design D7), not Jinja.

    `_CaptureTarget` does NOT execute the collector shell, so the recorded
    command is the full rendered template — both hostname and IPv4 endpoints
    carry the SAME template text (the `case` arms select `-servername` at shell
    runtime, which offline never runs). We therefore lock the *structure* of the
    SNI case branch in the command string:

      * the hostname arm `*[A-Za-z]*) sni="-servername $host"` is present,
      * the non-hostname (IPv4) arm sets `sni=""` (no SNI),
      * `$sni` is threaded into the `openssl s_client` invocation.

    The end-to-end correctness of the case branch (an IPv4 endpoint actually
    skipping SNI yet still validating the default chain) is NOT offline-provable
    here — it is covered by the real-host Demo Path (tasks.md §2.3 deviation
    register / §4.2).
    """

    hostname_cmd = _tls_main_cmd("tls_chain_validity_valid_openssl.json")
    ipv4_cmd = _tls_main_cmd("tls_chain_validity_valid_ipv4.json")

    for cmd in (hostname_cmd, ipv4_cmd):
        assert '*[A-Za-z]*) sni="-servername $host"' in cmd
        assert 'sni=""' in cmd
        assert "openssl s_client -connect" in cmd
        assert "$sni" in cmd

    # The only command-level difference between a hostname and an IPv4 endpoint
    # is the threaded endpoint value (the SNI decision itself is runtime `case`).
    assert "example.com:443" in hostname_cmd
    assert "1.1.1.1:443" in ipv4_cmd
