"""Snapshot tests for the wave-1 CPU + memory builtin inspectors.

`add-os-shell-inspectors-wave1` group 1 (pilot): `linux.cpu.throttling`,
`linux.cpu.cpufreq`, `linux.memory.swap`, `linux.memory.hugepages`.

These run the **real** `InspectorRunner` against `ReplayTarget` fixtures (see
`tests/inspectors/fixtures/os_compute_memory/`, generated by
`_record_os_compute_memory.py`), so they exercise the full
`preflight → render → collect → parse → findings` path **offline** — zero real
host, zero /proc, zero /sys read. The OS probes are Linux-only; the recorder
crafts the JSON each collector pipeline would emit per scenario.

Each inspector has BOTH an abnormal-scenario fixture (asserts a finding fires —
proving the inspector can detect the target fault, no no-op) and an ok-scenario
fixture (asserts zero findings). Every test asserts `replay.misses == []` so a
drift between the rendered command and the recorded fixture fails loud.
"""

from __future__ import annotations

from pathlib import Path

import structlog

from hostlens.core.config import Settings
from hostlens.inspectors.loader import load_manifest
from hostlens.inspectors.result import InspectorResult
from hostlens.inspectors.runner import InspectorRunner
from hostlens.targets.registry import TargetRegistry
from hostlens.targets.replay import ReplayTarget

_BUILTIN_DIR = (
    Path(__file__).resolve().parents[2] / "src" / "hostlens" / "inspectors" / "builtin" / "linux"
)
_FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "os_compute_memory"


def _logger() -> structlog.stdlib.BoundLogger:
    return structlog.get_logger("test")  # type: ignore[no-any-return]


def _runner() -> InspectorRunner:
    return InspectorRunner(TargetRegistry(), settings=Settings(), logger=_logger())


async def _run(inspector: str, fixture: str) -> tuple[ReplayTarget, InspectorResult]:
    manifest = load_manifest(_BUILTIN_DIR / f"{inspector}.yaml")
    replay = ReplayTarget("os-host", fixture=_FIXTURE_DIR / fixture)
    result = await _runner().run(manifest, replay)
    return replay, result


# --------------------------------------------------------------------------- #
# linux.cpu.throttling
# --------------------------------------------------------------------------- #


async def test_cpu_throttling_high_detected() -> None:
    replay, result = await _run("cpu_throttling", "cpu_throttling_high.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "nr_periods": 1000,
        "nr_throttled": 420,
        "throttled_usec": 12345678,
        "throttled_pct": "42.00",
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "CPU throttled in 42.00% of periods (420/1000)"),
    ]


async def test_cpu_throttling_ok_no_findings() -> None:
    replay, result = await _run("cpu_throttling", "cpu_throttling_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.cpu.cpufreq
# --------------------------------------------------------------------------- #


async def test_cpu_cpufreq_powersave_detected() -> None:
    replay, result = await _run("cpu_cpufreq", "cpu_cpufreq_powersave.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "governor": "powersave",
        "cur_freq_khz": 800000,
        "max_freq_khz": 3600000,
        "freq_pct": "22.2",
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("warning", "CPU scaling governor is 'powersave' (cpu0 at 22.2% of max clock)"),
        ("warning", "CPU clock capped low: cpu0 at 22.2% of max (governor=powersave)"),
    ]


async def test_cpu_cpufreq_ok_no_findings() -> None:
    replay, result = await _run("cpu_cpufreq", "cpu_cpufreq_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.memory.swap
# --------------------------------------------------------------------------- #


async def test_memory_swap_high_detected() -> None:
    replay, result = await _run("memory_swap", "memory_swap_high.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "swap_total_kb": 8388608,
        "swap_free_kb": 419430,
        "swappiness": 60,
        "swap_used_pct": "95.0",
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("critical", "Swap nearly exhausted at 95.0% used (swappiness=60)"),
    ]


async def test_memory_swap_ok_no_findings() -> None:
    replay, result = await _run("memory_swap", "memory_swap_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.memory.hugepages
# --------------------------------------------------------------------------- #


async def test_memory_hugepages_idle_detected() -> None:
    replay, result = await _run("memory_hugepages", "memory_hugepages_idle.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "hugepages_total": 1024,
        "hugepages_free": 1010,
        "hugepagesize_kb": 2048,
        "hugepages_free_pct": "98.6",
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("warning", "HugePages pool 1024 pages reserved but 98.6% idle (free)"),
    ]


async def test_memory_hugepages_ok_no_findings() -> None:
    replay, result = await _run("memory_hugepages", "memory_hugepages_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []
