"""Snapshot tests for the wave-1 systemd + cron builtin inspectors.

`add-os-shell-inspectors-wave1` group 5: `linux.systemd.timer_status`,
`linux.systemd.masked`, `linux.cron.last_runs`, `linux.cron.failures`.

These run the **real** `InspectorRunner` against `ReplayTarget` fixtures (see
`tests/inspectors/fixtures/os_systemd_cron/`, generated by
`_record_os_systemd_cron.py`), so they exercise the full
`preflight → render → collect → parse → findings` path **offline** — zero real
host, zero systemctl, zero journalctl. These probes are Linux + systemd only;
the recorder crafts the JSON/kv each collector pipeline would emit per scenario.

The cron inspectors declare `collect.sampling_window`, so the runner renders
`--since {window_start} --until {window_end}` into the command. The runner is
driven with the SAME frozen clock the recorder used so the rendered command is
byte-identical to the recorded fixture — `replay.misses == []` proves it.

Each inspector has BOTH an abnormal-scenario fixture (asserts a finding fires —
proving the inspector can detect the target fault, no no-op) and an ok-scenario
fixture (asserts zero findings).
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import structlog

from hostlens.core.config import Settings
from hostlens.inspectors.loader import load_manifest
from hostlens.inspectors.result import InspectorResult
from hostlens.inspectors.runner import InspectorRunner
from hostlens.targets.registry import TargetRegistry
from hostlens.targets.replay import ReplayTarget

_BUILTIN_DIR = (
    Path(__file__).resolve().parents[2] / "src" / "hostlens" / "inspectors" / "builtin" / "linux"
)
_FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "os_systemd_cron"


def _logger() -> structlog.stdlib.BoundLogger:
    return structlog.get_logger("test")  # type: ignore[no-any-return]


def _frozen_clock() -> datetime:
    return datetime(2024, 1, 2, 12, 0, 0, tzinfo=UTC)


def _runner() -> InspectorRunner:
    return InspectorRunner(
        TargetRegistry(), settings=Settings(), logger=_logger(), clock=_frozen_clock
    )


async def _run(inspector: str, fixture: str) -> tuple[ReplayTarget, InspectorResult]:
    manifest = load_manifest(_BUILTIN_DIR / f"{inspector}.yaml")
    replay = ReplayTarget("os-host", fixture=_FIXTURE_DIR / fixture)
    result = await _runner().run(manifest, replay)
    return replay, result


# --------------------------------------------------------------------------- #
# linux.systemd.timer_status
# --------------------------------------------------------------------------- #


async def test_systemd_timer_status_overdue_detected() -> None:
    replay, result = await _run("systemd_timer_status", "systemd_timer_status_overdue.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "results": [
            {
                "unit": "logrotate.timer",
                "next_elapse_usec": 0,
                "last_trigger_usec": 1700000000000000,
                "last_trigger_age_sec": 300000,
            },
            {
                "unit": "apt-daily.timer",
                "next_elapse_usec": 1704200000000000,
                "last_trigger_usec": 1704190000000000,
                "last_trigger_age_sec": 3600,
            },
        ]
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "warning",
            "systemd timer logrotate.timer has no next elapse scheduled and last fired 300000s ago",
        ),
    ]


async def test_systemd_timer_status_ok_no_findings() -> None:
    replay, result = await _run("systemd_timer_status", "systemd_timer_status_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.systemd.masked
# --------------------------------------------------------------------------- #


async def test_systemd_masked_present_detected() -> None:
    replay, result = await _run("systemd_masked", "systemd_masked_present.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "masked": [
            {"unit": "rsyslog.service"},
            {"unit": "apparmor.service"},
        ]
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        ("warning", "One or more systemd unit files are masked (see masked for details)"),
    ]


async def test_systemd_masked_none_no_findings() -> None:
    replay, result = await _run("systemd_masked", "systemd_masked_none.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"masked": []}
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.cron.last_runs
# --------------------------------------------------------------------------- #


async def test_cron_last_runs_stale_detected() -> None:
    replay, result = await _run("cron_last_runs", "cron_last_runs_stale.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "results": [
            {"command": "/usr/bin/refresh-cache", "last_run_age_sec": 120},
            {"command": "/usr/local/bin/backup.sh", "last_run_age_sec": 18000},
        ]
    }
    assert [(f.severity, f.message) for f in result.findings] == [
        (
            "warning",
            "cron job /usr/local/bin/backup.sh last ran 18000s ago (exceeds staleness threshold)",
        ),
    ]


async def test_cron_last_runs_ok_no_findings() -> None:
    replay, result = await _run("cron_last_runs", "cron_last_runs_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# linux.cron.failures
# --------------------------------------------------------------------------- #


async def test_cron_failures_spike_detected() -> None:
    replay, result = await _run("cron_failures", "cron_failures_spike.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"failure_count": "7", "window_seconds": "3600"}
    assert [(f.severity, f.message) for f in result.findings] == [
        ("warning", "7 cron failure log entries in the last 3600s"),
    ]


async def test_cron_failures_ok_no_findings() -> None:
    replay, result = await _run("cron_failures", "cron_failures_ok.json")

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"failure_count": "0", "window_seconds": "3600"}
    assert result.findings == []
