"""Snapshot tests for the ``mysql.deadlocks`` service inspector.

`add-nginx-upstream-mysql-deadlocks-inspectors` (wave-2b-tail): a point-in-time
"did an InnoDB deadlock occur within lookback" probe over
``SHOW ENGINE INNODB STATUS\\G``, secret ``HOSTLENS_MYSQL_PWD`` remapped to the
client-native ``MYSQL_PWD`` (never inlined in argv). The collector parses the
``LATEST DETECTED DEADLOCK`` section's ISO timestamp and collapses it to a
``deadlock_age_seconds`` scalar AT SAMPLE TIME (no-deadlock → ``-1`` sentinel so
both keys are always present and ``output_schema.required`` never fails).

These run the **real** ``InspectorRunner`` against ``ReplayTarget`` fixtures (see
``tests/inspectors/fixtures/mysql_deadlocks/``, generated by
``_record_mysql_deadlocks.py``), exercising the full
``preflight → render → collect → parse → findings`` path **offline** — zero real
MySQL. Non-root. Every test asserts ``replay.misses == []`` so any drift between
the rendered command and the recorded fixture fails loud.

Per design D-7 the collector shell (the LATEST DETECTED DEADLOCK awk
flag-on-marker / ISO-line offset, GNU ``date -d`` parse, age arithmetic) is NOT
executed under ReplayTarget — it is locked at the command-string level by the
verbatim fixture capture and verified behaviourally on the real-machine Demo
Path. This test does NOT claim to lock the awk/date correctness.

Failure-classification locks:
  * ``test_access_denied_fails_loud`` — auth failure → ``status=exception``
    (NOT a fabricated ``deadlock_detected=false`` healthy reading).
  * ``test_missing_mysql_binary_requires_unmet`` /
    ``test_missing_secret_env_requires_unmet`` — premise gaps →
    ``status=requires_unmet``.

Acceptance sufficiency rests on ``test_semantic_abnormal_warning`` (a real
deadlock whose age lands inside the DEFAULT ``lookback_seconds`` window crosses
the finding threshold); the no-deadlock fixture proves the ``-1`` sentinel path
lands ``ok`` with no finding.
"""

from __future__ import annotations

from pathlib import Path
from typing import ClassVar

import pytest
import structlog

import hostlens.inspectors as _inspectors_pkg
from hostlens.core.config import Settings
from hostlens.inspectors.loader import load_manifest
from hostlens.inspectors.result import InspectorResult
from hostlens.inspectors.runner import InspectorRunner
from hostlens.targets.base import Capability, ExecResult
from hostlens.targets.registry import TargetRegistry
from hostlens.targets.replay import ReplayTarget
from inspectors._record_mysql_deadlocks import RECORDED_PW

_FIXTURES = Path(__file__).parent / "fixtures" / "mysql_deadlocks"


def _builtin_root() -> Path:
    pkg_file = _inspectors_pkg.__file__
    assert pkg_file is not None
    return Path(pkg_file).parent / "builtin"


def _manifest_path() -> Path:
    return _builtin_root() / "mysql" / "deadlocks.yaml"


def _runner() -> InspectorRunner:
    return InspectorRunner(
        TargetRegistry(),
        settings=Settings(),
        logger=structlog.get_logger("mysql-deadlocks-test"),
    )


@pytest.fixture(autouse=True)
def _mysql_pwd_env(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("HOSTLENS_MYSQL_PWD", RECORDED_PW)


def test_manifest_loads_cleanly() -> None:
    manifest = load_manifest(_manifest_path())
    assert manifest.name == "mysql.deadlocks"
    assert manifest.parse.format == "json"
    assert manifest.requires_binaries == ["mysql"]
    assert manifest.secrets == ["HOSTLENS_MYSQL_PWD"]
    assert manifest.privilege == "none"
    assert "warn_count" not in manifest.parameters["properties"]  # type: ignore[index]
    assert all("+" not in tag for tag in manifest.tags)
    assert not (_manifest_path().parent / "hook.py").exists()


async def test_no_deadlock_no_findings() -> None:
    """No LATEST DETECTED DEADLOCK section → ``-1`` sentinel → ok, no finding."""

    manifest = load_manifest(_manifest_path())
    replay = ReplayTarget("mysqlrec", fixture=_FIXTURES / "no_deadlock.json")

    result = await _runner().run(manifest, replay, {"user": "root"})

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {
        "deadlock_detected": False,
        "deadlock_age_seconds": -1,
    }
    assert result.findings == []


async def test_semantic_abnormal_warning() -> None:
    """A real deadlock whose age is inside the DEFAULT ``lookback_seconds``
    window → warning at DEFAULT thresholds — genuine point-in-time deadlock
    state, not a lowered threshold."""

    manifest = load_manifest(_manifest_path())
    replay = ReplayTarget("mysqlrec", fixture=_FIXTURES / "semantic_abnormal.json")
    lookback_default = manifest.parameters["properties"]["lookback_seconds"]["default"]  # type: ignore[index]

    result = await _runner().run(manifest, replay, {"user": "root"})

    assert replay.misses == []
    assert result.status == "ok"
    assert result.output["deadlock_detected"] is True
    assert 0 <= result.output["deadlock_age_seconds"] <= lookback_default
    assert [f.severity for f in result.findings] == ["warning"]
    assert str(result.output["deadlock_age_seconds"]) in result.findings[0].message


async def test_access_denied_fails_loud() -> None:
    """Auth failure (wrong password) → status=exception, NOT a fabricated
    ``deadlock_detected=false`` healthy reading."""

    manifest = load_manifest(_manifest_path())
    replay = ReplayTarget("mysqlrec", fixture=_FIXTURES / "access_denied.json")

    result = await _runner().run(manifest, replay, {"user": "root"})

    assert replay.misses == []
    assert result.status == "exception"
    assert result.output == {}
    assert result.findings == []


def test_secret_not_in_rendered_command_or_output() -> None:
    """The injected ``HOSTLENS_MYSQL_PWD`` value must never appear in a recorded
    command string or its stdout (secret reaches the collector only via
    ``env=secrets_env``, remapped to the client-native ``MYSQL_PWD``)."""

    import json

    for fixture in sorted(_FIXTURES.glob("*.json")):
        data = json.loads(fixture.read_text(encoding="utf-8"))
        for command in data["commands"]:
            assert RECORDED_PW not in command["cmd"], fixture
            assert RECORDED_PW not in command["stdout"], fixture
            assert RECORDED_PW not in command["stderr"], fixture
            assert " -p" not in command["cmd"], (fixture, command["cmd"])


class _NoBinaryTarget:
    """Stub target where every ``command -v X`` probe fails (binary absent)."""

    type = "local"
    name = "no-binary-host"
    capabilities: ClassVar[set[Capability]] = {Capability.SHELL}

    async def exec(
        self,
        cmd: str,
        *,
        timeout: int,
        env: dict[str, str] | None = None,
    ) -> ExecResult:
        del timeout, env
        if cmd.startswith("command -v "):
            return ExecResult(
                exit_code=1, stdout="", stderr="", duration_seconds=0.0, timed_out=False
            )
        raise AssertionError(f"collector must not run when mysql is absent: {cmd!r}")

    async def read_file(self, path: str) -> bytes:
        raise AssertionError(f"read_file must not be reached: {path!r}")


async def test_missing_mysql_binary_requires_unmet() -> None:
    """A target without the mysql client → preflight requires_unmet skip."""

    manifest = load_manifest(_manifest_path())
    target = _NoBinaryTarget()

    result: InspectorResult = await _runner().run(manifest, target, {"user": "root"})  # type: ignore[arg-type]

    assert result.status == "requires_unmet"
    assert result.findings == []
    assert any(m.startswith("bin:") for m in result.missing), result.missing


async def test_missing_secret_env_requires_unmet(monkeypatch: pytest.MonkeyPatch) -> None:
    """A declared secret absent from the environment → preflight requires_unmet."""

    monkeypatch.delenv("HOSTLENS_MYSQL_PWD", raising=False)
    manifest = load_manifest(_manifest_path())
    replay = ReplayTarget("mysqlrec", fixture=_FIXTURES / "no_deadlock.json")

    result = await _runner().run(manifest, replay, {"user": "root"})

    assert result.status == "requires_unmet"
    assert result.missing == ["env:HOSTLENS_MYSQL_PWD"]
    assert result.output == {}
